### ISSUE TITLE
Can't add media to content types

### ISSUE THREAD

**Issue by Tramsi** [m3ntorship/charity#357]
**Issue:**
Failed to load media objects in the media library with one or more corrupted media objects.

**How to reproduce:**
1. Create a new content type `x` with a single media field
2. Create a new content entry in `x` and upload an image
3. Manually delete the generated directory for the content type `x` in `/api/x`
4. Delete build and cache directories
5. Run the Strapi server with `yarn develop`
6. Open media library

**Behavior:**
You should see toast message `an error occurred`
System logs:
```
error MissingSchemaError: Schema hasn't been registered for model "x".
```

**Root cause:**
Deleting the generated Strapi code for `x` content type does not cascade related data deletion. The image that got uploaded in step (2) was not cleaned up which was related to the deleted content type `x`. 

Opening the media library fetches all media objects where Strapi fails to load objects that have relation to content types that don't exist.

**Comment by kderbalah** [comment]
**Solution**:
Stale data should be cleaned-up along with deleting related content types.

**How to delete stale data:**
- Delete the content type and then delete the stale data from the DB console.
OR
- Delete the associated media objects from the content type entries before deleting the content type.

The issue has been solved with the first options as the second option was not applicable.
