### ISSUE TITLE
News & Articles Section need to match with the design

### ISSUE THREAD

**Issue by MAlngaawy** [m3ntorship/charity#91]
1_ Articles Photos size
2_ Articles details need to be like the design and in the middle of the photo
3_ and hover effect need to fix

**Comment by zahraa-khalil** [comment]
Thanks @MAlngaawy for initiating the issue ... 

May I add some extra concerns such: 
- the background png image needs repositioning.
- please, make sure that ur section is aligned properly with the below one

Happy coding :))
